"""empty message

Revision ID: 9999745327d5
Revises: 70028b275bc0
Create Date: 2024-06-16 03:32:47.587458

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy  # Add this import



# revision identifiers, used by Alembic.
revision = '9999745327d5'
down_revision = '70028b275bc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###